/**
 * Fund a Phoenix trader authority from a USDC-holding wallet, with no
 * Jupiter swap. Two pool ops (SOL leg + USDC leg) — the simplest, lowest-
 * fee path through Cloak when the user already holds USDC.
 *
 * Privacy property: T receives both inflows via Cloak pool unshields.
 * No on-chain edge from W to T.
 *
 * Library:
 *   import { fundTargetFromUsdc } from "../rise/index.js";
 *   await fundTargetFromUsdc({ connection, W, T, tSol: 0.05, tUsdc: 20 });
 *
 * CLI (env-driven, runs main()):
 *   W_KEYPAIR_PATH=/path/to/W.json
 *   TARGET_KEYPAIR_PATH=/path/to/T.json
 *   SOLANA_RPC_URL=https://your-mainnet-rpc
 *   T_SOL=0.05 T_USDC=20
 *   npx tsx src/fund-target-from-usdc.ts
 */

import {
  CLOAK_PROGRAM_ID,
  NATIVE_SOL_MINT,
  createUtxo,
  createZeroUtxo,
  fullWithdraw,
  generateUtxoKeypair,
  getNkFromUtxoPrivateKey,
  setCircuitsPath,
  transact,
} from "@cloak.ag/sdk";
import { Connection, Keypair, PublicKey } from "@solana/web3.js";
import { getAssociatedTokenAddress } from "@solana/spl-token";

import { preCloakFee } from "./lib/fees.js";
import { type Signer, signerPublicKey, toSdkSignerOptions } from "./lib/signer.js";

const USDC_MINT = new PublicKey("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v");
const DEFAULT_CIRCUITS = "https://cloak-circuits.s3.us-east-1.amazonaws.com/circuits/0.1.0";

export interface FundTargetFromUsdcOptions {
  /** Solana RPC connection (mainnet). */
  connection: Connection;
  /** Funding wallet. Either a Keypair (script) or a wallet adapter (browser). */
  W: Signer;
  /**
   * Target wallet (Keypair). Optional — if omitted, a fresh one is
   * generated and returned in the result. T must always be a Keypair
   * because subsequent perp-side calls sign with it; we don't support
   * trader-via-adapter (and don't want to — the privacy property
   * benefits from T being a fresh, ephemeral key).
   *
   * Caller is responsible for persisting the returned Keypair locally
   * (e.g., localStorage, file). The SDK never transmits it.
   */
  T?: Keypair;
  /** SOL amount delivered to T after Cloak fee, in SOL units (e.g. 0.05). */
  tSol: number;
  /** USDC amount delivered to T's ATA after Cloak fee, in USDC units. */
  tUsdc: number;
  /** Override the Cloak shield-pool program id. Defaults to mainnet. */
  programId?: PublicKey;
  /** Override the Cloak relay URL. Defaults to https://api.cloak.ag (SDK default). */
  relayUrl?: string;
  /** Circuits URL override (defaults to Cloak's hosted bundle). */
  circuitsUrl?: string;
  /** Progress callback. */
  onProgress?: (stage: string, status: string) => void;
}

export interface FundTargetResult {
  W: string;
  T: string;
  /** Returned so callers can persist a generated T locally. Always present. */
  TKeypair: Keypair;
  /** True if T was generated by this call (caller MUST persist `TKeypair`). */
  TGenerated: boolean;
  T_usdc_ata: string;
  T_sol_lamports_after: number;
  T_usdc_ui_after: string;
  swaps_used: number;
  direct_W_to_T_transfers: 0;
}

export async function fundTargetFromUsdc(opts: FundTargetFromUsdcOptions): Promise<FundTargetResult> {
  setCircuitsPath(opts.circuitsUrl ?? DEFAULT_CIRCUITS);
  const { connection, W, tSol, tUsdc, onProgress } = opts;

  // Auto-generate T if absent. Callers MUST persist the returned Keypair.
  const TGenerated = opts.T === undefined;
  const T: Keypair = opts.T ?? Keypair.generate();
  const wPubkey = signerPublicKey(W);
  const sdkSigner = toSdkSignerOptions(W);

  const tSolLamports = BigInt(Math.round(tSol * 1_000_000_000));
  const tUsdcBase = BigInt(Math.round(tUsdc * 1_000_000));
  const tSolPreFee = preCloakFee(tSolLamports);
  const tUsdcPreFee = preCloakFee(tUsdcBase);

  const wUsdcAta = await getAssociatedTokenAddress(USDC_MINT, wPubkey);
  const tUsdcAta = await getAssociatedTokenAddress(USDC_MINT, T.publicKey);

  // Pre-flight balance checks.
  const wSol = await connection.getBalance(wPubkey);
  const minSol = Number(tSolPreFee) + 50_000_000;
  if (wSol < minSol) {
    throw new Error(
      `W underfunded on SOL: ${wSol} lamports, need ≥ ${minSol} ` +
      `(T leg ${tSolPreFee} + ~0.05 SOL for W's tx fees)`,
    );
  }
  let wUsdc: bigint;
  try {
    wUsdc = BigInt((await connection.getTokenAccountBalance(wUsdcAta)).value.amount);
  } catch {
    throw new Error(`W has no USDC ATA at ${wUsdcAta.toBase58()}`);
  }
  if (wUsdc < tUsdcPreFee) {
    throw new Error(
      `W underfunded on USDC: ${wUsdc} base units, need ≥ ${tUsdcPreFee}`,
    );
  }

  // SOL leg: shield → unshield T_SOL.
  const solUtxoKp = await generateUtxoKeypair();
  const solNk = getNkFromUtxoPrivateKey(solUtxoKp.privateKey);
  onProgress?.("sol", "shielding");
  const solDep = await transact(
    {
      inputUtxos: [await createZeroUtxo()],
      outputUtxos: [await createUtxo(tSolPreFee, solUtxoKp, NATIVE_SOL_MINT)],
      externalAmount: tSolPreFee,
      depositor: wPubkey,
    },
    {
      connection, programId: opts.programId ?? CLOAK_PROGRAM_ID, ...(opts.relayUrl ? { relayUrl: opts.relayUrl } : {}), ...sdkSigner,
      chainNoteViewingKeyNk: solNk,
      onProgress: (s) => onProgress?.("sol-shield", s),
    },
  );
  await fullWithdraw([solDep.outputUtxos[0]], T.publicKey, {
    connection, programId: opts.programId ?? CLOAK_PROGRAM_ID, ...(opts.relayUrl ? { relayUrl: opts.relayUrl } : {}), ...sdkSigner,
    chainNoteViewingKeyNk: solNk, cachedMerkleTree: solDep.merkleTree,
    onProgress: (s) => onProgress?.("sol-withdraw", s),
  });

  // USDC leg: shield → unshield T_USDC. No swap.
  const usdcUtxoKp = await generateUtxoKeypair();
  const usdcNk = getNkFromUtxoPrivateKey(usdcUtxoKp.privateKey);
  onProgress?.("usdc", "shielding");
  const usdcDep = await transact(
    {
      inputUtxos: [await createZeroUtxo(USDC_MINT)],
      outputUtxos: [await createUtxo(tUsdcPreFee, usdcUtxoKp, USDC_MINT)],
      externalAmount: tUsdcPreFee,
      depositor: wPubkey,
    },
    {
      connection, programId: opts.programId ?? CLOAK_PROGRAM_ID, ...(opts.relayUrl ? { relayUrl: opts.relayUrl } : {}), ...sdkSigner,
      chainNoteViewingKeyNk: usdcNk,
      onProgress: (s) => onProgress?.("usdc-shield", s),
    },
  );
  await fullWithdraw([usdcDep.outputUtxos[0]], T.publicKey, {
    connection, programId: opts.programId ?? CLOAK_PROGRAM_ID, ...(opts.relayUrl ? { relayUrl: opts.relayUrl } : {}), ...sdkSigner,
    chainNoteViewingKeyNk: usdcNk, cachedMerkleTree: usdcDep.merkleTree,
    onProgress: (s) => onProgress?.("usdc-withdraw", s),
  });

  const tSolAfter = await connection.getBalance(T.publicKey);
  let tUsdcAfter = "0";
  for (let i = 0; i < 30; i++) {
    try {
      tUsdcAfter = (await connection.getTokenAccountBalance(tUsdcAta)).value.uiAmountString ?? "0";
      break;
    } catch { await new Promise((r) => setTimeout(r, 1000)); }
  }

  return {
    W: wPubkey.toBase58(),
    T: T.publicKey.toBase58(),
    TKeypair: T,
    TGenerated,
    T_usdc_ata: tUsdcAta.toBase58(),
    T_sol_lamports_after: tSolAfter,
    T_usdc_ui_after: tUsdcAfter,
    swaps_used: 0,
    direct_W_to_T_transfers: 0,
  };
}
